version: '3.9'

services:
  app:
    container_name: fast-api-app
    depends_on:
      - postgres
    build:
      context: .
      target: final
    command: ["/bin/bash", "/app/entrypoint.sh"]
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:5000"
    networks:
      - fast-api-dev

  postgres:
    container_name: fast-api-postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - fast-api-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  fast-api-dev:
    driver: bridge

volumes:
  postgres-data:
    driver: local

